### ISSUE TITLE
Can't find in the terminus settings plugin page

### ISSUE THREAD

**Issue by scrossan-crown** [kbjr/terminus-scrollbar#1]
Can't find the scroll bar in the plugin page.

![image](https://user-images.githubusercontent.com/30405149/42157017-83fc0218-7de4-11e8-95f8-9ea074eafb03.png)
![image](https://user-images.githubusercontent.com/30405149/42157096-b5ac6514-7de4-11e8-9e5e-59c2f8b49b6e.png)

**Comment by kbjr** [comment]
I'm aware, seems to be an npm issue. The keyword is on the package, npm just never returns it.

**Comment by kbjr** [comment]
In the meantime, you can always install it manually

**Comment by scrossan-crown** [comment]
Ok, I'll install it manually. Thanks

**Comment by Eugeny** [comment]
Should be working now with the latest Alpha

**Comment by scrossan-crown** [comment]
Yes, thank you. It’s now showing in the plugins list. I’m enjoying using it.


[cid:image001.jpg@01D41847.CF34B6B0]

Scott Crossan
Developer
t: 01617621819
s.crossan@crownoil.co.uk<mailto:s.crossan@crownoil.co.uk>
www.crownoil.co.uk<http://www.crownoil.co.uk/>

[Description: cid:BBDC52DE-BFB3-4947-AEC4-D900A598E80F]
